routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\ResultImportController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/dashboard/{id}/class', [DashboardController::class, 'classResult'])->name('classResult');

    Route::resource('schoolclasses', SchoolClassController::class);

    Route::resource('subjects', SubjectController::class);
    Route::get('subjects/{id}/class', [SubjectController::class, 'classSubjects'])->name('classSubjects');

    Route::resource('students', StudentController::class);
    Route::get('students/{id}/class', [StudentController::class, 'classStudents'])->name('classStudents');

    Route::resource('results', ResultController::class);

    Route::get('result/{id}/show', [ResultController::class, 'singleResult'])->name('single');

    Route::get('student/exl-import', [StudentImportController::class, 'create'])->name('exlImport');
    Route::post('student/exl-store', [StudentImportController::class, 'store'])->name('exlStore');

    Route::get('result/exl-import', [ResultImportController::class, 'create'])->name('resultImport');
    Route::post('result/exl-store', [ResultImportController::class, 'store'])->name('resultStore');

    Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
});

require __DIR__.'/auth.php';

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    use HasFactory;

    protected $fillable = [
        'subject',
    ];

    public function classes ()
    {
        return $this->belongsToMany(School_class::class);
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use Illuminate\Http\Request;
use App\Http\Requests\SubjectRequest;
use App\Models\School_class;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$data['subjects'] = Subject::with('classes')->get();
        //dd($data);
        $data['classes'] = School_class::all();
        $data['clsSubjects'] = null;
        return view('subjects.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['classes'] = School_class::pluck('name','id');
        return view('subjects.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubjectRequest $request)
    {
        //dd($request->input());
        $subject = Subject::create([
            'subject' => $request->get('subject'),
        ]);

        if (empty($subject)) {
            return redirect()->back()->withInput();
        }
        $subject->classes()->attach($request->get('class_ids'));

        return redirect()
        ->route('subjects.index')
        ->with('SUCCESS', __('Class has been created.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        return redirect()->back()->with('ERROR', __('Nothing to show.'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        $data['subject'] = $subject;
        $data['classes'] = School_class::pluck('name','id');
        //dd($data);
        return view('subjects.edit', $data);
        //return redirect()->back()->with('ERROR', __('Edit not allowed.'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {   //dd($request->input());
        $subject->subject = $request->get('subject');


        if($subject->update()){
            $subject->classes()->sync($request->get('class_ids'));
            return redirect()->route('subjects.index')->with('SUCCESS', __('Subject has been Updated.'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Fail to Updated.'));
        //return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        if($subject->classes()->detach()){
            $subject->delete();
            return redirect()->back()->with('SUCCESS', __('Subject has been deleted.'));
        }
        return redirect()->back()->with('ERROR', __('Please try again.'));

    }

    public function classSubjects ($id)
    {
        $data['classes'] = School_class::all();
        $data['clsSubjects'] = School_class::with('subjects')->where('id', $id)->first();

        return view('subjects.index',$data);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/subjects/_form.blade.php
<div class="mb-4">
    <label class="block" for="category">Class</label>
    <select name="class_ids[]" id="class_id" multiple="true">
        <option >{{ __("Select Class")}}</option>
        @foreach ($classes as $id => $name)
            {{-- <option value="{{ $id }}" >
                {{ $name }}
            </option> --}}
            <option @isset($subject)
                        {{$subject->classes->firstWhere("name",$name) ? "selected=true" : ""}}
                    @endisset value="{{ $id }}" >
                {{ $name }}
            </option>
        @endforeach
    </select>
    <p class=" text-red-500">{{$errors->first("class_id")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Subject</label>
    <input class="focus" type="text" name="subject" value="{{ old('subject', isset($subject) ? $subject->subject : '')}}" id="name">
    <p class=" text-red-500">{{$errors->first("subject")}}</p>
</div>
<div>
    <a class="p-1 pl-3 pr-3 bg-transparent border-2 border-gray-500 text-gray-500 text-lg rounded-lg hover:bg-gray-500 hover:text-gray-100 focus:border-4 focus:border-gray-300" href="{{ route('subjects.index')}}">Back</a>

    <button class="p-1 pl-7 pr-7 bg-transparent border-2 border-green-500 text-green-500 text-lg rounded-lg hover:bg-green-500 hover:text-gray-100 focus:border-4 focus:border-green-300" type="submit">{{$buttonText}}</button>
</div>

resources/views/subjects/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Subject') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("subjects.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include("subjects._form",["buttonText" => __("Create")])

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/subjects/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Class') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("subjects.update", $subject->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        @include("subjects._form",["buttonText" => __("Update")])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/subjects/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Subjects') }}
            </h2>
            @if ($clsSubjects != null)
                <h2 class="px-10 py-1 font-semibold leading-tight text-gray-700 bg-gray-100 rounded-sm">{{$clsSubjects->name}} subjects list</h2>
            @endif
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('subjects.create')}}">Create Subject</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @forelse ($classes as $class)
                    <a href="{{route('classSubjects',$class->id)}}" class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm">{{$class->name}}</a>
                    @empty
                        <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No class found.")}}</td>
                        </tr>
                    @endforelse

                    @if ($clsSubjects != null)
                    {{-- <h2 class="font-semibold text-xxl text-gray-800 leading-tight">{{$clsSubjects->name}}</h2> --}}
                    <table class="w-full mt-4">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Subject </th>
                            <th class="px-4 py-3">Action</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">

                          @forelse ($clsSubjects->subjects as $clsSubject)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $clsSubject->id}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$clsSubject->subject}}</td>
                            <td class="py-3 px-4 border">
                                <a href="{{route('subjects.edit',$clsSubject->id)}}" class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm">Edit</a>
                                <a href="{{route('subjects.destroy', $clsSubject->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No subject found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                    @endif
                      <div class="my-4">
                           {{-- {{$categories->links()}} --}}
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>