routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\ResultImportController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/dashboard/{id}/class', [DashboardController::class, 'classResult'])->name('classResult');

    Route::resource('schoolclasses', SchoolClassController::class);

    Route::resource('subjects', SubjectController::class);
    Route::get('subjects/{id}/class', [SubjectController::class, 'classSubjects'])->name('classSubjects');

    Route::resource('students', StudentController::class);
    Route::get('students/{id}/class', [StudentController::class, 'classStudents'])->name('classStudents');

    Route::resource('results', ResultController::class);

    Route::get('result/{id}/show', [ResultController::class, 'singleResult'])->name('single');

    Route::get('student/exl-import', [StudentImportController::class, 'create'])->name('exlImport');
    Route::post('student/exl-store', [StudentImportController::class, 'store'])->name('exlStore');

    Route::get('result/exl-import', [ResultImportController::class, 'create'])->name('resultImport');
    Route::post('result/exl-store', [ResultImportController::class, 'store'])->name('resultStore');

    Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
});

require __DIR__.'/auth.php';

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable = [
        'roll',
        'class_id',
        'name',
        'email',
    ];

    public function class ()
    {
        return $this->hasOne(School_class::class, 'id','class_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use App\Models\School_class;
use Illuminate\Http\Request;
use App\Http\Requests\StudentRequest;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['classes'] = School_class::all();
        $data['students'] = null;

        return view('students.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['classes'] = School_class::pluck('name','id');

        return view('students.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $student = Student::create([
            'roll' => $request->get('roll'),
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'class_id' => $request->get('class_id'),
        ]);

        if(empty($student)){
            return redirect()->back()->withInput();
        }

        return redirect()
        ->route('students.index')
        ->with('SUCCESS', __('Student has been created.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    public function classStudents ($id)
    {
        $data['classes'] = School_class::all();
        $data['students'] = Student::with('class')->where('class_id', $id)->get();

        return view('students.index',$data);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/students/_form.blade.php
<div class="mb-4">
    <label class="block" for="category">Class</label>
    <select name="class_id" id="class_id" >
        <option value="">{{ __("Select Class")}}</option>
        @foreach ($classes as $id => $name)
            <option value="{{ $id }}" >
                {{ $name }}
            </option>
        @endforeach
    </select>
    <p class=" text-red-500">{{$errors->first("class_id")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Student Name</label>
    <input class="focus" type="text" name="name" value="{{ old('name', isset($subject) ? $subject->name : '')}}" id="name">
    <p class=" text-red-500">{{$errors->first("name")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Student Email</label>
    <input class="focus" type="text" name="email" value="{{ old('email', isset($subject) ? $subject->email : '')}}" id="name">
    <p class=" text-red-500">{{$errors->first("email")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Student Roll</label>
    <input class="focus" type="number" name="roll" value="{{ old('roll', isset($subject) ? $subject->roll : '')}}" id="name">
    <p class=" text-red-500">{{$errors->first("roll")}}</p>
</div>
<div>
    <a class="p-1 pl-3 pr-3 bg-transparent border-2 border-gray-500 text-gray-500 text-lg rounded-lg hover:bg-gray-500 hover:text-gray-100 focus:border-4 focus:border-gray-300" href="{{ route('students.index')}}">Back</a>

    <button class="p-1 pl-7 pr-7 bg-transparent border-2 border-green-500 text-green-500 text-lg rounded-lg hover:bg-green-500 hover:text-gray-100 focus:border-4 focus:border-green-300" type="submit">{{$buttonText}}</button>
</div>

resources/views/students/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Student') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("students.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include("students._form",["buttonText" => __("Create")])

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/students/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Class') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("schoolclasses.update", $sclClass->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        @include("classes._form",["buttonText" => __("Update")])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/students/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Students') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm" href="{{ route('exlImport')}}">Import student</a>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('students.create')}}">Create student</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @forelse ($classes as $class)
                    <a href="{{route('classStudents',$class->id)}}" class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm">{{$class->name}}</a>
                    @empty
                        <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No class found.")}}</td>
                        </tr>
                    @endforelse
                    @if ($students != null)
                    <table class="w-full mt-4">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Class</th>
                            <th class="px-4 py-3">Roll</th>
                            <th class="px-4 py-3">Name</th>
                            <th class="px-4 py-3">Email</th>
                            <th class="px-4 py-3">Action</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">
                          @forelse ($students as $student)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $student->id}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$student->class->name}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$student->roll}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$student->name}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$student->email}}</td>
                            <td class="py-3 px-4 border">
                                <a href="{{route('students.edit',$student->id)}}" class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm">Edit</a>
                                <a href="{{route('students.destroy', $student->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No students found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                    @endif

                      <div class="my-4">
                           {{-- {{$categories->links()}} --}}
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>