routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\ResultImportController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/dashboard/{id}/class', [DashboardController::class, 'classResult'])->name('classResult');

    Route::resource('schoolclasses', SchoolClassController::class);

    Route::resource('subjects', SubjectController::class);
    Route::get('subjects/{id}/class', [SubjectController::class, 'classSubjects'])->name('classSubjects');

    Route::resource('students', StudentController::class);
    Route::get('students/{id}/class', [StudentController::class, 'classStudents'])->name('classStudents');

    Route::resource('results', ResultController::class);

    Route::get('result/{id}/show', [ResultController::class, 'singleResult'])->name('single');

    Route::get('student/exl-import', [StudentImportController::class, 'create'])->name('exlImport');
    Route::post('student/exl-store', [StudentImportController::class, 'store'])->name('exlStore');

    Route::get('result/exl-import', [ResultImportController::class, 'create'])->name('resultImport');
    Route::post('result/exl-store', [ResultImportController::class, 'store'])->name('resultStore');

    Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
});

require __DIR__.'/auth.php';

app/Models/Result.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    use HasFactory;

    protected $fillable = [
        'mark',
        'class_id',
        'student_id',
        'subject_id',
    ];

    public function student() {

        return $this->belongsTo(Student::class, 'student_id');
    }

    public function subjects() {

        return $this->belongsTo(Subject::class, "subject_id","id");
    }

    public function sclClass() {

        return $this->belongsTo(School_class::class,"class_id","id");
    }

}

app/Http/Controllers/ResultController.php
<?php

namespace App\Http\Controllers;

use App\Models\Result;
use App\Models\Student;
use App\Models\Subject;
use App\Models\School_class;
use Illuminate\Http\Request;
use App\Http\Requests\ResultRequest;

class ResultController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['results'] = Result::with('student','sclClass')
        ->groupBy('student_id')
        ->selectRaw('sum(mark) as marks, student_id,id,class_id')
        ->orderByRaw('SUM(mark) DESC')
        ->get();

        return view('results.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['classes'] = School_class::pluck('name','id');
        $data['students'] = Student::pluck('name','id');
        $data['subjects'] = Subject::pluck('subject','id');

        //dd($data);

        return view('results.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ResultRequest $request)
    {
        $result = Result::where('student_id', $request->get('student_id'))
        ->where('subject_id', $request->get('subject_id'))->first();

        if ($result) {
        return redirect()->back()->withInput()->with('ERROR', __('Result already added.'));
        }

        $subject = $request->get('subject_id');
        $mark = $request->get('mark');

        for($i=0; $i<count($subject);$i++){
            $data = [
                'class_id' => $request->get('class_id'),
                'student_id' => $request->get('student_id'),
                'subject_id' => $subject[$i],
                'mark' => $mark[$i],
            ];
            $create = Result::create($data);
        }

        if(empty($create)) {
            return redirect()->back()->withInput()->with("ERROR", __("Pleace input again"));
        }
        return redirect()->route('results.index')->with("SUCCESS", __("Marks Added successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function show(Result $result)
    {
        //dd($result);
        // $data['results'] = Result::where('class_id', $result->class_id)
        // ->with('student')
        // //->groupBy('student_id')
        // ->selectRaw('sum(mark) as marks, student_id,id,class_id')
        // ->orderByRaw('SUM(mark) DESC')->get();
        // //dd($data);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function edit(Result $result)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Result $result)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function destroy(Result $result)
    {
        return redirect()->back()->with('ERROR', __('Do not try this.'));

    }

    public function singleResult ($id)
    {
        $data['student'] = Student::where('id', $id)->first();
        $data['results'] = Result::with('subjects')->where('student_id', $id)->get();
        $data['totalMark'] = 0;
        foreach ($data['results'] as $result) {
            $data['totalMark'] +=  $result['mark'];
        }
        //dd($data['totalMark']);
        return view('results.single', $data);
    }

    public function getClassId($id) {

        $studentClass = Student::where('class_id', $id)->pluck('name','id');
        // dd($studentClass);

        // return json_encode($studentClass);
        return response()->json($studentClass);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/results/_form.blade.php
<div class="mb-4">
    <label class="block" for="category">Class</label>
    <select name="class_id" id="class_id" >
        <option value="">{{ __("Select Class")}}</option>
        @foreach ($classes as $id => $name)
            <option value="{{ $id }}" >
                {{ $name }}
            </option>
        @endforeach
    </select>
    <p class=" text-red-500">{{$errors->first("class_id")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="category">Student</label>
    <select name="student_id" id="student_id" >
        <option value="">{{ __("Select student")}}</option>

    </select>
    <p class=" text-red-500">{{$errors->first("student_id")}}</p>
</div>

@forelse ($subjects as $id => $subject)
<div class="mb-4">
    <label class="block" for="task" >{{ $subject }}</label>
    <input class="focus" type="hidden"  name="subject_id[]" value="{{ $id}}" id="subject_id">
    <input class="focus" type="text"  name="mark[]" id="mark">
    <p class=" text-red-500">{{$errors->first("mark.*")}}</p>
</div>
@empty

@endforelse
<div>
    <a class="p-1 pl-3 pr-3 bg-transparent border-2 border-gray-500 text-gray-500 text-lg rounded-lg hover:bg-gray-500 hover:text-gray-100 focus:border-4 focus:border-gray-300" href="{{ route('results.index')}}">Back</a>

    <button class="p-1 pl-7 pr-7 bg-transparent border-2 border-green-500 text-green-500 text-lg rounded-lg hover:bg-green-500 hover:text-gray-100 focus:border-4 focus:border-green-300" type="submit">{{$buttonText}}</button>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('select[name="class_id"]').on('change', function() {
            var classID = jQuery(this).val();
            if (classID) {
                jQuery.ajax({
                    // url: '/getclassid/' + classID,
                    url: "/getclassid/" + classID,
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        console.log(data);
                        jQuery('select[name="student_id"]').empty();
                        jQuery('select[name="student_id"]').append(
                            '<option>Select Students</option>');
                        jQuery.each(data, function(key, value) {
                            $('select[name="student_id"]').append('<option value="' + key +
                                '">' + value + '</option>');
                        });
                    }
                });
            } else {
                $('select[name="student_id"]').empty();
                $('select[name="student_id"]').append('<option>No Students Found</option>');
            }
        });
    });
    </script>

resources/views/results/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Student') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("results.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include("results._form",["buttonText" => __("Create")])

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/results/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Class') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("schoolclasses.update", $sclClass->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        @include("classes._form",["buttonText" => __("Update")])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/results/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Results') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm" href="{{ route('resultImport')}}">Import Result</a>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('results.create')}}">Create Result</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="w-full">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Class</th>
                            <th class="px-4 py-3">Name</th>
                            <th class="px-4 py-3">Total Mark</th>
                            <th class="px-4 py-3">Action</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">
                          @forelse ($results as $result)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $result->id}}</td>
                            {{-- <td class="px-4 py-3 text-ms font-semibold border">{{$result->mark}}</td> --}}
                            <td class="px-4 py-3 text-ms font-semibold border">{{$result->sclClass->name}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$result->student->name}}</td>

                            <td class="px-4 py-3 text-ms font-semibold border">{{$result->marks}}</td>

                            <td class="py-3 px-4 border">
                                <a href="{{route('results.edit',$result->id)}}" class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm">Edit</a>
                                <a href="{{route('results.destroy', $result->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No result found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                      <div class="my-4">
                           {{-- {{$categories->links()}} --}}
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/results/single-class.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Results') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('results.create')}}">Create Result</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="w-full">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Name</th>
                            <th class="px-4 py-3">Total Mark</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">
                          @forelse ($results as $result)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $result->id}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$result->student->name}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$result->marks}}</td>

                            <td class="py-3 px-4 border">
                                <a href="{{route('results.edit',$result->id)}}" class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm">Edit</a>
                                <a href="{{route('results.destroy', $result->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No result found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                      <div class="my-4">
                           {{-- {{$categories->links()}} --}}
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/results/single.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Student Result') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('classResult', $student->class->id)}}">All Result</a>

        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="w-full">
                        <tr class="text-gray-700">
                            <td class="py-3 px-4 ">
                                Class: {{$student->class->name}}
                            </td>
                        </tr>
                        <tr class="text-gray-700">
                            <td class="py-3 px-4 ">
                                Name: {{$student->name}}
                            </td>
                        </tr>
                        <tr class="text-gray-700">
                            <td class="py-3 px-4 ">
                                Email: {{$student->email}}
                            </td>
                        </tr>
                        @foreach ($results as $result)
                        <tr class="text-gray-700">
                            <td class="py-3 px-4 ">
                                {{$result->subjects->subject}}: {{$result->mark}}
                            </td>
                        </tr>
                        @endforeach
                        <tr class="text-blue-700">
                            <td class="py-3 px-4">Total Mark: {{ $totalMark }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>