routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\ResultImportController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/dashboard/{id}/class', [DashboardController::class, 'classResult'])->name('classResult');

    Route::resource('schoolclasses', SchoolClassController::class);

    Route::resource('subjects', SubjectController::class);
    Route::get('subjects/{id}/class', [SubjectController::class, 'classSubjects'])->name('classSubjects');

    Route::resource('students', StudentController::class);
    Route::get('students/{id}/class', [StudentController::class, 'classStudents'])->name('classStudents');

    Route::resource('results', ResultController::class);

    Route::get('result/{id}/show', [ResultController::class, 'singleResult'])->name('single');

    Route::get('student/exl-import', [StudentImportController::class, 'create'])->name('exlImport');
    Route::post('student/exl-store', [StudentImportController::class, 'store'])->name('exlStore');

    Route::get('result/exl-import', [ResultImportController::class, 'create'])->name('resultImport');
    Route::post('result/exl-store', [ResultImportController::class, 'store'])->name('resultStore');

    Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/classes/_form.blade.php
<div class="mb-4">
    <label class="block" for="task">Class</label>
    <input class="focus" type="text" name="name" value="{{ old('name', isset($sclClass) ? $sclClass->name : '')}}" id="name">
    <p class=" text-red-500">{{$errors->first("name")}}</p>
</div>
<div>
    <a class="p-1 pl-3 pr-3 bg-transparent border-2 border-gray-500 text-gray-500 text-lg rounded-lg hover:bg-gray-500 hover:text-gray-100 focus:border-4 focus:border-gray-300" href="{{ route('schoolclasses.index')}}">Back</a>

    <button class="p-1 pl-7 pr-7 bg-transparent border-2 border-green-500 text-green-500 text-lg rounded-lg hover:bg-green-500 hover:text-gray-100 focus:border-4 focus:border-green-300" type="submit">{{$buttonText}}</button>
</div>

resources/views/classes/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Class') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("schoolclasses.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include("classes._form",["buttonText" => __("Create")])

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/classes/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Class') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("schoolclasses.update", $sclClass->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        @include("classes._form",["buttonText" => __("Update")])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/classes/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Classes') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('schoolclasses.create')}}">Create Class</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="w-full">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Class</th>
                            <th class="px-4 py-3">Action</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">
                          @forelse ($classes as $sclClass)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $sclClass->id}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$sclClass->name}}</td>
                            <td class="py-3 px-4 border">
                                <a href="{{route('schoolclasses.edit',$sclClass->id)}}" class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm">Edit</a>
                                <a href="{{route('schoolclasses.destroy', $sclClass->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No Classes found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                      <div class="my-4">
                           {{-- {{$categories->links()}} --}}
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>